---

- name: Install cryptsetup
  apt: name=cryptsetup update_cache=yes cache_valid_time=3600

- name: Allocate swap space
  command: >
    fallocate -l {{ swap_size }} {{ swap_location }}
    creates={{ swap_location }}
  register: allocate_swap

- name: Restrict swap permissions
  file: path={{ swap_location }} mode=0600

- name: Configure swap to be encrypted
  lineinfile: >
    dest=/etc/crypttab
    line="cryptswap {{ swap_location }} /dev/urandom swap"

- name: Restart cryptdisks
  service: name=cryptdisks state=restarted

- name: Mount swap on reboot
  mount: src={{ swap_location }} name=none fstype=swap opts=sw dump=0 passno=0 state=present

- name: Set swappiness
  sysctl: name=vm.swappiness value={{ swap_swappiness }} reload=yes

- name: Make swap
  command: mkswap {{ swap_location }}
  when: allocate_swap.changed

- name: Activate swap
  command: swapon {{ swap_location }}
  when: allocate_swap.changed
