---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install UFW
  apt: name=ufw state=latest

- name: Open SSH port and enable rate limiting
  ufw: rule=limit port={{ ssh_port }}

- name: Enable firewall
  ufw: state=enabled logging=on

- name: Install fail2ban
  apt: name=fail2ban state=latest

- name: Copy fail2ban configuration
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local

- name: Restart fail2ban
  service: name=fail2ban state=restarted

- name: Create SSH user with sudo permission
  user: name="{{ ssh_user }}" groups=sudo shell=/bin/bash
  when: ssh_add_user

- name: Allow user to sudo without a password
  lineinfile: >
    dest=/etc/sudoers
    line="{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL"
    state=present
    validate='visudo -cf %s'

- name: Add SSH pubkey
  authorized_key: >
    user="{{ ssh_user }}"
    key="{{ lookup('file', ssh_key_path) }}"
  when: ssh_add_key

- name: Disable SSH root login
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present

- name: Disable SSH password authentication
  lineinfile: 
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present

#- name: Restart SSH daemon
#  service: name=ssh state=restarted

# Workaround for bug in Ubuntu 14.04
- name: Restart SSH daemon
  shell: service ssh restart

- name: Install updates daily
  cron: >
    name="install updates"
    special_time=daily
    user=root
    job="apt-get update && apt-get -y upgrade"
