---

- name: Install fail2ban
  apt: name=fail2ban state=latest
  tags: ['ssh', 'ssh:fail2ban', 'ssh:fail2ban:install']

- name: Enable fail2ban
  service: name=fail2ban enabled=yes
  tags: ['ssh', 'ssh:fail2ban', 'ssh:fail2ban:install']

- name: Copy fail2ban configuration
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban
  tags: ['ssh', 'ssh:fail2ban', 'ssh:fail2ban:configuration']
