---

- name: Create SSH user
  user:
    name={{ ssh_user }}
    groups={{ ssh_user_groups }}
    shell={{ ssh_user_shell }}
    password={{ ssh_user_pass }}
  when: ssh_user != ''
  tags: ['ssh', 'ssh:user']

- name: Set user password
  user:
    name={{ ssh_user }}
    password={{ ssh_user_pass }}
  when: ssh_user != '' and ssh_user_pass != ''
  tags: ['ssh', 'ssh:user']

- name: Allow user to sudo without a password
  lineinfile: >
    dest=/etc/sudoers
    line="{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL"
    state=present
    validate='visudo -cf %s'
  when: ssh_user != '' and ssh_user_pass == '' and 'sudo' in ssh_user_groups
  tags: ['ssh', 'ssh:user']

- name: Add SSH public keys
  authorized_key: >
    user={{ ssh_user }}
    key={{ item }}
  with_items: ssh_public_keys
  when: ssh_user != ''
  tags: ['ssh', 'ssh:user']

- name: Disable SSH root login
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present
  notify: reload ssh
  tags: ['ssh', 'ssh:configuration']

- name: Disable SSH password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify: reload ssh
  tags: ['ssh', 'ssh:configuration']

- name: Open SSH port and enable rate limiting
  ufw: rule=limit port={{ ssh_port }}
  tags: ['ssh', 'ssh:configuration']
