---

- name: Add Tor repository
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - "deb http://deb.torproject.org/torproject.org trusty main"
    - "deb-src http://deb.torproject.org/torproject.org trusty main"

- name: Add Tor repository key
  apt_key: keyserver=keys.gnupg.net id=886DDD89

- name: Update apt cache
  apt: update_cache=yes

- name: Install Tor
  apt: name={{ item }} state=latest
  with_items:
    - tor
    - deb.torproject.org-keyring

- name: Copy Tor configuration file
  template: src=torrc.j2 dest=/etc/tor/torrc

- name: Open Tor port
  ufw: rule=allow port={{ tor_port }}

- name: Restart Tor
  service: name=tor state=restarted
