---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: ['common']

- name: Install packages
  apt: name={{ item }} state=latest
  with_items: common_packages
  tags: ['common', 'common:install']

- name: Install UFW
  apt: name=ufw state=latest
  tags: ['common', 'common:install']

- name: Enable UFW at end of playbook
  command: 'true'
  notify: enable ufw
  tags: ['common', 'common:install']
